FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    tesseract-ocr \
    tesseract-ocr-por \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.ocr.txt .
RUN pip install --no-cache-dir -r requirements.ocr.txt

COPY app/modules/ocr ./ocr_service.py

CMD ["uvicorn", "ocr_service:app", "--host", "0.0.0.0", "--port", "8001"]
