web: gunicorn app.main:app --workers $((2 * $(nproc) + 1)) --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --access-logfile - --error-logfile - --log-level info
release: alembic upgrade head
